#!/bin/bash
gen_interval=$1

export_vec() {
    module=$1
    name=$2
    filename=./results/${module}_${name}_${gen_interval}.csv
    opp_scavetool x ./results/General-#0.vec -F CSV-S -o $filename -f "module=~$module AND name=~$name"
    sed -i '1d' $filename
}

sed -i "s/exponential\(.*\)/exponential\($gen_interval\)/" ./omnetpp.ini
make MODE=release
./lab3 -u Cmdenv
export_vec Network.nodeTx.traTx SentPackets
export_vec Network.nodeTx.traTx BufferSize
export_vec Network.nodeRx.traRx BufferSize
export_vec Network.nodeRx.sink ReceivedPackets
export_vec Network.nodeRx.sink Delay